name: ghpages_generator
version: 0.2.0
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: This package allows to generate gh-pages branch for Github with dartdoc and examples
homepage: https://github.com/a14n/dart-ghpages-generator
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  path: '>=1.0.0 <2.0.0'
