name: ghpages_generator
version: 0.3.0
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: This package allows to generate gh-pages branch for Github with dartdoc and examples
homepage: https://github.com/a14n/dart-ghpages-generator
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  args: '>=0.12.0 <0.14.0'
  path: '>=1.0.0 <2.0.0'
executables:
  generate_ghpages: generate
  generate_ghpages_with_web: generate_with_web
