name: publish_ghpages
version: 0.0.1-dev
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: This package allows to publish a site on Github with dartdoc and examples
homepage: https://github.com/a14n/dart-publish-gh-pages
dependencies:
  path: any
dev_dependencies:
  unittest: any
