name: ghpages_generator
version: 0.0.4-dev
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: This package allows to generate gh-pages branch for Github with dartdoc and examples
homepage: https://github.com/a14n/dart-ghpages-generator
dependencies:
  path: any
